# This file was generated by GoReleaser. DO NOT EDIT.
cask "mactl" do
  name "mactl"
  desc "mactl: CLI to quickly bootstrap macbooks"
  homepage "https://github.com/leftbin/mactl"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mactl"

  on_macos do
    on_intel do
      url "https://github.com/leftbin/mactl/releases/download/v#{version}/mactl_#{version}_darwin_amd64.tar.gz"
      sha256 "832d286f8ff2d53365aab524a0a5fe3ef4721fb6d6020415dfe44a73beb69a07"
    end
    on_arm do
      url "https://github.com/leftbin/mactl/releases/download/v#{version}/mactl_#{version}_darwin_arm64.tar.gz"
      sha256 "dd337548f892468d20f440ffd96cb981e52eaa8966e9e37b282910e537038ff4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mactl"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "mactl helps you quickly bootstrap and configure macOS machines."
    ""
    "Quick Start"
    ""
    "1. Bootstrap your Mac with essential tools:"
    "   mactl bootstrap run"
    ""
    "2. List available apps:"
    "   mactl app list"
    ""
    "3. Add an app:"
    "   mactl app add <app-name>"
    ""
    "4. Configure git:"
    "   mactl git config init"
    ""
    "For more commands, run:"
    "   mactl --help"
    ""
    "Documentation: https://github.com/leftbin/mactl"
  end

  # No zap stanza required
end
